otto:
  api: 1
  tasks: [ci]
  envs:
    VERSION: "$(git describe --tags --always --dirty 2>/dev/null || echo 'dev')"

tasks:
  # Whitespace linting
  lint:
    help: "Run whitespace linting"
    bash: |
      whitespace -r

  # Code quality checks
  check:
    help: "Run all quality checks (compile, clippy, format)"
    bash: |
      echo "=== Checking compilation ==="
      cargo check --all-targets --all-features
      echo ""
      echo "=== Running Clippy ==="
      cargo clippy --all-targets --all-features -- -D warnings
      echo ""
      echo "=== Checking format ==="
      cargo fmt --all --check
      echo ""
      echo "✅ All checks passed!"

  # Run tests
  test:
    help: "Run all tests"
    bash: |
      cargo test --all-features

  # Code coverage with llvm-cov
  cov:
    help: "Run tests with coverage via llvm-cov (use --fail-under N for threshold)"
    params:
      --fail-under:
        default: "0"
        help: "Minimum line coverage percentage (0 = no threshold)"
    bash: |
      echo "🧪 Running tests with coverage..."
      if [ "${fail_under}" != "0" ]; then
        if cargo llvm-cov --all-features --html -q --fail-under-lines "${fail_under}"; then
          echo ""
          echo "✅ Coverage meets ${fail_under}% threshold"
          echo "📊 Coverage report: target/llvm-cov/html/index.html"
        else
          echo ""
          echo "❌ Coverage is below ${fail_under}% threshold"
          echo "📊 Coverage report: target/llvm-cov/html/index.html"
          exit 1
        fi
      else
        cargo llvm-cov --all-features --html -q
        echo ""
        echo "✅ Coverage report: target/llvm-cov/html/index.html"
      fi

  # Full CI pipeline
  ci:
    help: "Full CI pipeline (lint + check + test in parallel)"
    before: [lint, check, test]
    bash: |
      echo "✅ All CI checks passed!"

  # Build release binary
  build:
    help: "Build release binary"
    bash: |
      cargo build --release
      echo "✅ Release build complete"

  # Clean build artifacts
  clean:
    help: "Clean build artifacts"
    bash: |
      cargo clean
      echo "✅ Build artifacts cleaned"

  # Install locally
  install:
    help: "Install binary locally via cargo"
    bash: |
      cargo install --path .
      echo "✅ Binary installed to ~/.cargo/bin"

  # Run CLI examples
  examples:
    help: "Run all CLI usage examples"
    bash: |
      echo "=== Running Engram CLI Examples ==="
      echo ""

      # Build release binary
      echo "Building engram binary..."
      cargo build --release --quiet
      export PATH="$PWD/target/release:$PATH"
      echo ""

      # Run each example
      failed=0
      for example in examples/*.sh; do
        name=$(basename "$example")
        echo "--- Running $name ---"
        if EXAMPLE_DIR=$(mktemp -d) bash "$example"; then
          echo "✅ $name passed"
        else
          echo "❌ $name failed"
          failed=$((failed + 1))
        fi
        echo ""
      done

      if [ $failed -eq 0 ]; then
        echo "✅ All examples passed!"
      else
        echo "❌ $failed example(s) failed"
        exit 1
      fi

